export const dashboardCards = [
  { title: "Sekretariat Jenderal", value: "95.26", color: "bg-[#6FCE00]" },
  { title: "Inspektorat Jenderal", value: "97.21", color: "bg-[#6FCE00]" },
  { title: "Ditjen Banapenta dan PKK", value: "93.63", color: "bg-[#2E70FD]" },//F1E528
  { title: "PHI dan Jamsostek", value: "95.18", color: "bg-[#6FCE00]" },
  { title: "Binwasnaker dan K3", value: "93.06", color: "bg-[#2E70FD]" },
  { title: "Barenbang Ketenagakerjaan", value: "91.65", color: "bg-[#2E70FD]" },
  { title: "Binalavotas", value: "92.32", color: "bg-[#2E70FD]" },
];

export const dataTable = {
  columns: [
    { label: "Eselon 1", key: "Eselon 1" },
    { label: "Revisi DIPA (10%)", key: "Revisi DIPA (10%)" },
    { label: "Deviasi Hal III Dipa (15%)", key: "Deviasi Hal III Dipa (15%)" },
    { label: "Realisasi Anggaran (20%)", key: "Realisasi Anggaran (20%)" },
    { label: "Belanja Kontraktual (10%)", key: "Belanja Kontraktual (10%)" },
    { label: "Penyelesaian Tagihan (10%)", key: "Penyelesaian Tagihan (10%)" },
    { label: "Pengelolaan UP & TUP (10%)", key: "Pengelolaan UP & TUP (10%)" },
    { label: "Dispensasi SPM (Pengurang)", key: "Dispensasi SPM (Pengurang)" },
    { label: "Capaian Output (25%)", key: "Capaian Output (25%)" },
    {
      label: "Nilai IKPA",
      key: "Nilai IKPA",
      style: "bg-[#2E70FD] rounded p-2 text-white",
    },
  ],
  data: [
    {
      eselon: "Kementerian Ketenagakerjaan",
      revisiDipa: 100,
      deviasiHalIII: 70.41,
      realisasiAnggaran: 99.78,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 97.33,
      capaianOutput: 100,
      nilaiIKPA: 95.25,
    },
    {
      eselon: "Sekretariat Jenderal",
      revisiDipa: 100,
      deviasiHalIII: 94,
      realisasiAnggaran: 81.70,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 98.21,
      capaianOutput: 100,
      nilaiIKPA: 95.26,
    },
    {
      eselon: "Inspektorat Jenderal",
      revisiDipa: 100,
      deviasiHalIII: 92.68,
      realisasiAnggaran: 93.04,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 97,
      capaianOutput: 100,
      nilaiIKPA: 97.21,
    },
    {
      eselon: "Ditjen Binapenta",
      revisiDipa: 100,
      deviasiHalIII: 81.9,
      realisasiAnggaran: 81.88,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 99.72,
      capaianOutput: 100,
      nilaiIKPA: 93.63,
    },
    {
      eselon: "PHI dan Jamsostek",
      revisiDipa: 100,
      deviasiHalIII: 67.87,
      realisasiAnggaran: 100,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 100,
      capaianOutput: 100,
      nilaiIKPA: 95.18,
    },
    {
      eselon: "Binwasnaker dan K3",
      revisiDipa: 100,
      deviasiHalIII: 81.45,
      realisasiAnggaran: 79.27,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 99.85,
      capaianOutput: 100,
      nilaiIKPA: 93.06,
    },
    {
      eselon: "Barenbang Ketenagakerjaan",
      revisiDipa: 100,
      deviasiHalIII: 74.25,
      realisasiAnggaran: 79.40,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 96.29,
      capaianOutput: 100,
      nilaiIKPA: 91.65,
    },
    {
      eselon: "Binalavotas",
      revisiDipa: 100,
      deviasiHalIII: 75.61,
      realisasiAnggaran: 82.09,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 95.56,
      capaianOutput: 100,
      nilaiIKPA: 92.32,
    }
  ],
};
